name: Update README with Latest Hashnode Blog

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allows you to manually trigger the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Fetch Latest Blog Post from Hashnode
      env:
        HASHNODE_TOKEN: ${{ secrets.HASHNODE_TOKEN }}
      run: |
        curl -X POST \
          -H "Authorization: Bearer $HASHNODE_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"query":"{user(username: \"kartikshukla\") {publication {posts(page: 0) {title, brief, slug}}}}"}' \
          https://api.hashnode.com/ \
          > response.json

    - name: Print response.json for debugging
      run: cat response.json

    - name: Update README
      run: |
        BLOG_TITLE=$(jq -r '.data.user.publication.posts[0].title' response.json)
        BLOG_SLUG=$(jq -r '.data.user.publication.posts[0].slug' response.json)
        BLOG_URL="https://kartikshukla.hashnode.dev/$BLOG_SLUG"
        sed -i "s|<!-- BLOGS -->|### [${BLOG_TITLE}](${BLOG_URL})\n<!-- BLOGS -->|" README.md

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m 'Update README with latest Hashnode blog post'
        git push
